"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const factura_1 = require("../controllers/factura");
const router = (0, express_1.Router)();
router.get('/', factura_1.getAll);
router.get('/:id', factura_1.getById);
router.get('/resumen/:id', factura_1.getResumen);
router.delete('/:id', factura_1.deleteFactura);
router.post('/', factura_1.postFactura);
router.put('/:id', factura_1.updateFactura);
exports.default = router;
